expiry: 23713
maximumRisk: 30.0
#spring:
#    data:
#        mongodb:
#            database: TradeStore
#            host: localhost
#            port: 27017



spring:
    data:
        mongodb:
            uri : mongodb://kite:kite@ac-kyt3lxu-shard-00-00.zgiaxhc.mongodb.net:27017,ac-kyt3lxu-shard-00-01.zgiaxhc.mongodb.net:27017,ac-kyt3lxu-shard-00-02.zgiaxhc.mongodb.net:27017/?replicaSet=atlas-1b3jyw-shard-0&ssl=true&authSource=admin
            database : TradeStore

